### ISSUE TITLE
Guilds

### ISSUE THREAD

**Issue by XanderID** [jinix6/free-ff-api#5]
are there API Guild Wars Points? or Guilds Information

**Comment by jinix6** [comment]
In the future, coming soon!

**Comment by XanderID** [comment]
Can I Participate in Development?

**Comment by jinix6** [comment]
Currently, it's just me working on this project. I appreciate your interest, though! Stay tuned for updates.

**Comment by jinix6** [comment]
> are there API Guild Wars Points? or Guilds Information

[Guild Information](https://github.com/jinix6/free-ff-api#-guild-information)
